// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgvPUDk9DtnifCVuseXHobnb4Rh4vGaY',
    appId: '1:331633196228:web:d81a7efb50ffc6c831dd91',
    messagingSenderId: '331633196228',
    projectId: 'myjodi-c45b0',
    authDomain: 'myjodi-c45b0.firebaseapp.com',
    databaseURL: 'https://myjodi-c45b0-default-rtdb.firebaseio.com',
    storageBucket: 'myjodi-c45b0.appspot.com',
    measurementId: 'G-0EQJ5MDG47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkHoiMsfkiIVYBxEuLzfoP9GwtRGskuaE',
    appId: '1:331633196228:android:a05eeedb15faa85931dd91',
    messagingSenderId: '331633196228',
    projectId: 'myjodi-c45b0',
    databaseURL: 'https://myjodi-c45b0-default-rtdb.firebaseio.com',
    storageBucket: 'myjodi-c45b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvxFSHMeCut-gB5tm_rnOdN-9a-ZJ3vMc',
    appId: '1:331633196228:ios:d6efc643a88ef92d31dd91',
    messagingSenderId: '331633196228',
    projectId: 'myjodi-c45b0',
    databaseURL: 'https://myjodi-c45b0-default-rtdb.firebaseio.com',
    storageBucket: 'myjodi-c45b0.appspot.com',
    androidClientId: '331633196228-sj76pk2hcfnfd0m0kqtohf46lkf0nl1v.apps.googleusercontent.com',
    iosClientId: '331633196228-lc2vobodestjtopa32oetqoampucjius.apps.googleusercontent.com',
    iosBundleId: 'com.myjodi.admin.myJodiAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvxFSHMeCut-gB5tm_rnOdN-9a-ZJ3vMc',
    appId: '1:331633196228:ios:d6efc643a88ef92d31dd91',
    messagingSenderId: '331633196228',
    projectId: 'myjodi-c45b0',
    databaseURL: 'https://myjodi-c45b0-default-rtdb.firebaseio.com',
    storageBucket: 'myjodi-c45b0.appspot.com',
    androidClientId: '331633196228-sj76pk2hcfnfd0m0kqtohf46lkf0nl1v.apps.googleusercontent.com',
    iosClientId: '331633196228-lc2vobodestjtopa32oetqoampucjius.apps.googleusercontent.com',
    iosBundleId: 'com.myjodi.admin.myJodiAdmin',
  );
}
